### ISSUE TITLE
Order

### ISSUE THREAD

**Issue by MegamiSoftware** [astral-cool/Server#9]
Hey, thanks for the reply to my last issue.
I'd like to ask: In what order to I install things?
Like do I do bot first, then server, then frontend. I don't get it.

**Comment by aspectiscool** [comment]
The order doesn't matter

**Comment by MegamiSoftware** [comment]
Ok, and do I use 
npm run start
npm run build even on bot and other things?

**Comment by aspectiscool** [comment]
make a .env file, fill out all the required fields,
npm run build
npm run start

**Comment by MegamiSoftware** [comment]
Sorry for asking so stupidly but can I dm ya on Discord? I need a bit of more help, I still appreciate the support here tho.

**Comment by aspectiscool** [comment]
sure, aspect#2288

**Comment by MegamiSoftware** [comment]
request sent, [øš]Џu◕α®♫Ø平仮名#8100
